name: CI/CD for Flutter App

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: macos-latest
    steps:
      - name: check Xcode version
        run: /usr/bin/xcodebuild -version
        
      - name: Checkout code
        uses: actions/checkout@v4

      # - uses: actions/setup-java@v4
      #   with:
      #     distribution: 'temurin'
      #     java-version: '17'
      #     cache: 'gradle'
      #     cache-dependency-path: |
      #       android/*.gradle*
      #       android/**/gradle-wrapper.properties

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.5'
          cache: true

      # - uses: actions/cache@v4
      #   with:
      #     path: |
      #       ~/.gradle/caches
      #       ~/.gradle/wrapper
      #     key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
      #     restore-keys: |
      #       ${{ runner.os }}-gradle-
      
      - name: Install dependencies
        run: flutter pub get

      - name: Build iOS
        if: runner.os == 'macOS'
        run: flutter build ipa --release

      # - name: Build Android
      #   run: flutter build apk --release

      # - name: Upload APK
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: android-apk  # Tên artifact hiển thị trên GitHub
      #     path: build/app/outputs/flutter-apk/app-release.apk  # Đường dẫn đến file APK
