name: CI/CD for Flutter App

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'

      - name: Setup Flutter
        uses: subosito/flutter-action@v1
        with:
          flutter-version: '3.24.5'
      
      - name: Install dependencies
        run: flutter pub get

      - name: Build Android
        run: flutter build apk --release

      - name: Build iOS
        if: runner.os == 'macOS'
        run: flutter build ipa --release
